"$schema" = 'https://starship.rs/config-schema.json'

format = """
${custom.face}\
[](bg:#3f72af fg:#a3aed2)\
$directory\
[](fg:#3f72af bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#3f72af bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = "[[ $symbol $branch ](fg:#a2d2ff bg:#394260)]($style)"

[git_status]
style = "bg:#394260"
format = "[[($all_status$ahead_behind )](fg:#a2d2ff bg:#394260)]($style)"

[nodejs]
symbol = ""
style = "bg:#212736"
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"

[rust]
symbol = ""
style = "bg:#212736"
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"

[golang]
symbol = ""
style = "bg:#212736"
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"

[php]
symbol = ""
style = "bg:#212736"
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230"
format = "[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)"

[custom.face]
command = "echo \"(';')\""
when = "true"
style = "bold bg:#a3aed2 fg:#000000"
format = "[ $output ]($style)"
