[manager]
sort_by        = "natural"
sort_sensitive = false # 大文字小文字を区別せずソート
sort_reverse   = false
sort_dir_first = true # ディレクトリを先に、ファイルを後に表示
show_hidden    = true
scryp          = ["*.tmp", ".git"] # 特定の拡張子を隠す
