# PATHやLANG、EDITORなど「どんな場面でも反映させたい環境変数の設定」
# .zshenvには重い処理やエイリアス・プロンプト設定などは書かない
# → すべてのzsh起動で必ず実行されるので、最低限の「いつでも必要な設定」だけにしましょう

# 個人的に追加したパッケージを優先的に扱うため /usr/local/bin にパスを通す
export PATH=/usr/local/bin:$PATH

# fzfのプレビュー内で実行された新規シェルにも自作ラッパーが反映されるために追加
export PATH="$HOME/dotfiles/zsh/bin:$PATH"

# Rust製commandを使えるようにする為
source "$HOME/.cargo/env"

# デフォルトのエディター
export EDITOR=nvim

# 文字コードの指定
export LANG=ja_JP.UTF-8
